### ISSUE TITLE
mendel-daemon is terminated because of memory issue

### ISSUE THREAD

**Issue by muralikr** [yahoo/mendel#137] opened 2017-06-19 23:36 UTC
Randomly, daemon process is quit with following error message. It doesn't seem to be related to sync or any file changes. Sometimes, it is terminated right after startup. This has been happening frequently with latest package updates.

```
<--- Last few GCs --->
 1537981 ms: Scavenge 733.7 (1434.6) -> 733.6 (1434.6) MB, 2.7 / 0 ms [allocation failure].
 1537984 ms: Scavenge 733.9 (1434.6) -> 733.8 (1434.6) MB, 2.6 / 0 ms [allocation failure].
 1537987 ms: Scavenge 733.9 (1434.6) -> 733.8 (1434.6) MB, 3.0 / 0 ms [allocation failure].
 1537990 ms: Scavenge 734.0 (1434.6) -> 734.0 (1434.6) MB, 2.5 / 0 ms [allocation failure].
 1537993 ms: Scavenge 734.1 (1434.6) -> 734.1 (1434.6) MB, 2.6 / 0 ms [allocation failure].
<--- JS stacktrace --->
Cannot get stack trace in GC.
FATAL ERROR: Scavenger: semi-space copy
 Allocation failed - process out of memory
sh: line 1: 63295 Abort trap: 6           mendel --watch
```

**Comment by irae** [comment] 2017-06-19 23:52
Stephan investigated a bit and I am not sure why this would happen but he had some clues.

I don't have issues at all, but I don't use the amount of transforms you do and I don't use babel. All my Mendel process summed up take very few memory.

<img width="815" alt="screen shot 2017-06-10 at 10 10 58 am" src="https://user-images.githubusercontent.com/98254/27310497-046de296-5531-11e7-83ab-00db752313cd.png">

Also, we changed the transforms to use `package.json` so we didn't allocate the memory and used CPU on daemon.

Can you post updates as you investigate? I totally can't reproduce.

**Comment by irae** [comment] 2018-02-14 19:50
I'll close this one for now, since Mendel changed too much and none of current users are seeing the issue.

**Closed by irae** 2018-02-14 19:50 UTC
Labels: more-info-required
